# Generated by Django 2.1.15 on 2021-06-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210616_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
