# Generated by Django 2.1.15 on 2021-06-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210618_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profilePicture',
        ),
        migrations.AddField(
            model_name='profile',
            name='dbProfilePicture',
            field=models.BinaryField(blank=True),
        ),
    ]
